class Country {
  final String name;
  final String code; // ISO 2-letter
  final String dialCode;
  final String currency;
  final String flag;

  const Country({
    required this.name,
    required this.code,
    required this.dialCode,
    required this.currency,
    required this.flag,
  });

  // Comprehensive list of countries
  static const List<Country> all = [
    Country(
      name: 'Afghanistan',
      code: 'AF',
      dialCode: '+93',
      currency: 'AFN',
      flag: '🇦🇫',
    ),
    Country(
      name: 'Albania',
      code: 'AL',
      dialCode: '+355',
      currency: 'ALL',
      flag: '🇦🇱',
    ),
    Country(
      name: 'Algeria',
      code: 'DZ',
      dialCode: '+213',
      currency: 'DZD',
      flag: '🇩🇿',
    ),
    Country(
      name: 'American Samoa',
      code: 'AS',
      dialCode: '+1-684',
      currency: 'USD',
      flag: '🇦🇸',
    ),
    Country(
      name: 'Andorra',
      code: 'AD',
      dialCode: '+376',
      currency: 'EUR',
      flag: '🇦🇩',
    ),
    Country(
      name: 'Angola',
      code: 'AO',
      dialCode: '+244',
      currency: 'AOA',
      flag: '🇦🇴',
    ),
    Country(
      name: 'Anguilla',
      code: 'AI',
      dialCode: '+1-264',
      currency: 'XCD',
      flag: '🇦🇮',
    ),
    Country(
      name: 'Antigua and Barbuda',
      code: 'AG',
      dialCode: '+1-268',
      currency: 'XCD',
      flag: '🇦🇬',
    ),
    Country(
      name: 'Argentina',
      code: 'AR',
      dialCode: '+54',
      currency: 'ARS',
      flag: '🇦🇷',
    ),
    Country(
      name: 'Armenia',
      code: 'AM',
      dialCode: '+374',
      currency: 'AMD',
      flag: '🇦🇲',
    ),
    Country(
      name: 'Aruba',
      code: 'AW',
      dialCode: '+297',
      currency: 'AWG',
      flag: '🇦🇼',
    ),
    Country(
      name: 'Australia',
      code: 'AU',
      dialCode: '+61',
      currency: 'AUD',
      flag: '🇦🇺',
    ),
    Country(
      name: 'Austria',
      code: 'AT',
      dialCode: '+43',
      currency: 'EUR',
      flag: '🇦🇹',
    ),
    Country(
      name: 'Azerbaijan',
      code: 'AZ',
      dialCode: '+994',
      currency: 'AZN',
      flag: '🇦🇿',
    ),
    Country(
      name: 'Bahamas',
      code: 'BS',
      dialCode: '+1-242',
      currency: 'BSD',
      flag: '🇧🇸',
    ),
    Country(
      name: 'Bahrain',
      code: 'BH',
      dialCode: '+973',
      currency: 'BHD',
      flag: '🇧🇭',
    ),
    Country(
      name: 'Bangladesh',
      code: 'BD',
      dialCode: '+880',
      currency: 'BDT',
      flag: '🇧🇩',
    ),
    Country(
      name: 'Barbados',
      code: 'BB',
      dialCode: '+1-246',
      currency: 'BBD',
      flag: '🇧🇧',
    ),
    Country(
      name: 'Belarus',
      code: 'BY',
      dialCode: '+375',
      currency: 'BYN',
      flag: '🇧🇾',
    ),
    Country(
      name: 'Belgium',
      code: 'BE',
      dialCode: '+32',
      currency: 'EUR',
      flag: '🇧🇪',
    ),
    Country(
      name: 'Belize',
      code: 'BZ',
      dialCode: '+501',
      currency: 'BZD',
      flag: '🇧🇿',
    ),
    Country(
      name: 'Benin',
      code: 'BJ',
      dialCode: '+229',
      currency: 'XOF',
      flag: '🇧🇯',
    ),
    Country(
      name: 'Bermuda',
      code: 'BM',
      dialCode: '+1-441',
      currency: 'BMD',
      flag: '🇧🇲',
    ),
    Country(
      name: 'Bhutan',
      code: 'BT',
      dialCode: '+975',
      currency: 'BTN',
      flag: '🇧🇹',
    ),
    Country(
      name: 'Bolivia',
      code: 'BO',
      dialCode: '+591',
      currency: 'BOB',
      flag: '🇧🇴',
    ),
    Country(
      name: 'Bosnia and Herzegovina',
      code: 'BA',
      dialCode: '+387',
      currency: 'BAM',
      flag: '🇧🇦',
    ),
    Country(
      name: 'Botswana',
      code: 'BW',
      dialCode: '+267',
      currency: 'BWP',
      flag: '🇧🇼',
    ),
    Country(
      name: 'Brazil',
      code: 'BR',
      dialCode: '+55',
      currency: 'BRL',
      flag: '🇧🇷',
    ),
    Country(
      name: 'British Indian Ocean Territory',
      code: 'IO',
      dialCode: '+246',
      currency: 'USD',
      flag: '🇮🇴',
    ),
    Country(
      name: 'Brunei Darussalam',
      code: 'BN',
      dialCode: '+673',
      currency: 'BND',
      flag: '🇧🇳',
    ),
    Country(
      name: 'Bulgaria',
      code: 'BG',
      dialCode: '+359',
      currency: 'BGN',
      flag: '🇧🇬',
    ),
    Country(
      name: 'Burkina Faso',
      code: 'BF',
      dialCode: '+226',
      currency: 'XOF',
      flag: '🇧🇫',
    ),
    Country(
      name: 'Burundi',
      code: 'BI',
      dialCode: '+257',
      currency: 'BIF',
      flag: '🇧🇮',
    ),
    Country(
      name: 'Cambodia',
      code: 'KH',
      dialCode: '+855',
      currency: 'KHR',
      flag: '🇰🇭',
    ),
    Country(
      name: 'Cameroon',
      code: 'CM',
      dialCode: '+237',
      currency: 'XAF',
      flag: '🇨🇲',
    ),
    Country(
      name: 'Canada',
      code: 'CA',
      dialCode: '+1',
      currency: 'CAD',
      flag: '🇨🇦',
    ),
    Country(
      name: 'Cape Verde',
      code: 'CV',
      dialCode: '+238',
      currency: 'CVE',
      flag: '🇨🇻',
    ),
    Country(
      name: 'Cayman Islands',
      code: 'KY',
      dialCode: '+1-345',
      currency: 'KYD',
      flag: '🇰🇾',
    ),
    Country(
      name: 'Central African Republic',
      code: 'CF',
      dialCode: '+236',
      currency: 'XAF',
      flag: '🇨🇫',
    ),
    Country(
      name: 'Chad',
      code: 'TD',
      dialCode: '+235',
      currency: 'XAF',
      flag: '🇹🇩',
    ),
    Country(
      name: 'Chile',
      code: 'CL',
      dialCode: '+56',
      currency: 'CLP',
      flag: '🇨🇱',
    ),
    Country(
      name: 'China',
      code: 'CN',
      dialCode: '+86',
      currency: 'CNY',
      flag: '🇨🇳',
    ),
    Country(
      name: 'Christmas Island',
      code: 'CX',
      dialCode: '+61',
      currency: 'AUD',
      flag: '🇨🇽',
    ),
    Country(
      name: 'Colombia',
      code: 'CO',
      dialCode: '+57',
      currency: 'COP',
      flag: '🇨🇴',
    ),
    Country(
      name: 'Comoros',
      code: 'KM',
      dialCode: '+269',
      currency: 'KMF',
      flag: '🇰🇲',
    ),
    Country(
      name: 'Congo',
      code: 'CG',
      dialCode: '+242',
      currency: 'XAF',
      flag: '🇨🇬',
    ),
    Country(
      name: 'Democratic Republic of the Congo',
      code: 'CD',
      dialCode: '+243',
      currency: 'CDF',
      flag: '🇨🇩',
    ),
    Country(
      name: 'Cook Islands',
      code: 'CK',
      dialCode: '+682',
      currency: 'NZD',
      flag: '🇨🇰',
    ),
    Country(
      name: 'Costa Rica',
      code: 'CR',
      dialCode: '+506',
      currency: 'CRC',
      flag: '🇨🇷',
    ),
    Country(
      name: 'Côte d\'Ivoire',
      code: 'CI',
      dialCode: '+225',
      currency: 'XOF',
      flag: '🇨🇮',
    ),
    Country(
      name: 'Croatia',
      code: 'HR',
      dialCode: '+385',
      currency: 'HRK',
      flag: '🇭🇷',
    ),
    Country(
      name: 'Cuba',
      code: 'CU',
      dialCode: '+53',
      currency: 'CUP',
      flag: '🇨🇺',
    ),
    Country(
      name: 'Cyprus',
      code: 'CY',
      dialCode: '+357',
      currency: 'EUR',
      flag: '🇨🇾',
    ),
    Country(
      name: 'Czech Republic',
      code: 'CZ',
      dialCode: '+420',
      currency: 'CZK',
      flag: '🇨🇿',
    ),
    Country(
      name: 'Denmark',
      code: 'DK',
      dialCode: '+45',
      currency: 'DKK',
      flag: '🇩🇰',
    ),
    Country(
      name: 'Djibouti',
      code: 'DJ',
      dialCode: '+253',
      currency: 'DJF',
      flag: '🇩🇯',
    ),
    Country(
      name: 'Dominica',
      code: 'DM',
      dialCode: '+1-767',
      currency: 'XCD',
      flag: '🇩🇲',
    ),
    Country(
      name: 'Dominican Republic',
      code: 'DO',
      dialCode: '+1-809',
      currency: 'DOP',
      flag: '🇩🇴',
    ),
    Country(
      name: 'Ecuador',
      code: 'EC',
      dialCode: '+593',
      currency: 'USD',
      flag: '🇪🇨',
    ),
    Country(
      name: 'Egypt',
      code: 'EG',
      dialCode: '+20',
      currency: 'EGP',
      flag: '🇪🇬',
    ),
    Country(
      name: 'El Salvador',
      code: 'SV',
      dialCode: '+503',
      currency: 'USD',
      flag: '🇸🇻',
    ),
    Country(
      name: 'Equatorial Guinea',
      code: 'GQ',
      dialCode: '+240',
      currency: 'XAF',
      flag: '🇬🇶',
    ),
    Country(
      name: 'Eritrea',
      code: 'ER',
      dialCode: '+291',
      currency: 'ERN',
      flag: '🇪🇷',
    ),
    Country(
      name: 'Estonia',
      code: 'EE',
      dialCode: '+372',
      currency: 'EUR',
      flag: '🇪🇪',
    ),
    Country(
      name: 'Ethiopia',
      code: 'ET',
      dialCode: '+251',
      currency: 'ETB',
      flag: '🇪🇹',
    ),
    Country(
      name: 'Falkland Islands',
      code: 'FK',
      dialCode: '+500',
      currency: 'FKP',
      flag: '🇫🇰',
    ),
    Country(
      name: 'Faroe Islands',
      code: 'FO',
      dialCode: '+298',
      currency: 'DKK',
      flag: '🇫🇴',
    ),
    Country(
      name: 'Fiji',
      code: 'FJ',
      dialCode: '+679',
      currency: 'FJD',
      flag: '🇫🇯',
    ),
    Country(
      name: 'Finland',
      code: 'FI',
      dialCode: '+358',
      currency: 'EUR',
      flag: '🇫🇮',
    ),
    Country(
      name: 'France',
      code: 'FR',
      dialCode: '+33',
      currency: 'EUR',
      flag: '🇫🇷',
    ),
    Country(
      name: 'French Guiana',
      code: 'GF',
      dialCode: '+594',
      currency: 'EUR',
      flag: '🇬🇫',
    ),
    Country(
      name: 'French Polynesia',
      code: 'PF',
      dialCode: '+689',
      currency: 'XPF',
      flag: '🇵🇫',
    ),
    Country(
      name: 'Gabon',
      code: 'GA',
      dialCode: '+241',
      currency: 'XAF',
      flag: '🇬🇦',
    ),
    Country(
      name: 'Gambia',
      code: 'GM',
      dialCode: '+220',
      currency: 'GMD',
      flag: '🇬🇲',
    ),
    Country(
      name: 'Georgia',
      code: 'GE',
      dialCode: '+995',
      currency: 'GEL',
      flag: '🇬🇪',
    ),
    Country(
      name: 'Germany',
      code: 'DE',
      dialCode: '+49',
      currency: 'EUR',
      flag: '🇩🇪',
    ),
    Country(
      name: 'Ghana',
      code: 'GH',
      dialCode: '+233',
      currency: 'GHS',
      flag: '🇬🇭',
    ),
    Country(
      name: 'Gibraltar',
      code: 'GI',
      dialCode: '+350',
      currency: 'GIP',
      flag: '🇬🇮',
    ),
    Country(
      name: 'Greece',
      code: 'GR',
      dialCode: '+30',
      currency: 'EUR',
      flag: '🇬🇷',
    ),
    Country(
      name: 'Greenland',
      code: 'GL',
      dialCode: '+299',
      currency: 'DKK',
      flag: '🇬🇱',
    ),
    Country(
      name: 'Grenada',
      code: 'GD',
      dialCode: '+1-473',
      currency: 'XCD',
      flag: '🇬🇩',
    ),
    Country(
      name: 'Guadeloupe',
      code: 'GP',
      dialCode: '+590',
      currency: 'EUR',
      flag: '🇬🇵',
    ),
    Country(
      name: 'Guam',
      code: 'GU',
      dialCode: '+1-671',
      currency: 'USD',
      flag: '🇬🇺',
    ),
    Country(
      name: 'Guatemala',
      code: 'GT',
      dialCode: '+502',
      currency: 'GTQ',
      flag: '🇬🇹',
    ),
    Country(
      name: 'Guinea',
      code: 'GN',
      dialCode: '+224',
      currency: 'GNF',
      flag: '🇬🇳',
    ),
    Country(
      name: 'Guinea-Bissau',
      code: 'GW',
      dialCode: '+245',
      currency: 'XOF',
      flag: '🇬🇼',
    ),
    Country(
      name: 'Guyana',
      code: 'GY',
      dialCode: '+592',
      currency: 'GYD',
      flag: '🇬🇾',
    ),
    Country(
      name: 'Haiti',
      code: 'HT',
      dialCode: '+509',
      currency: 'HTG',
      flag: '🇭🇹',
    ),
    Country(
      name: 'Honduras',
      code: 'HN',
      dialCode: '+504',
      currency: 'HNL',
      flag: '🇭🇳',
    ),
    Country(
      name: 'Hong Kong',
      code: 'HK',
      dialCode: '+852',
      currency: 'HKD',
      flag: '🇭🇰',
    ),
    Country(
      name: 'Hungary',
      code: 'HU',
      dialCode: '+36',
      currency: 'HUF',
      flag: '🇭🇺',
    ),
    Country(
      name: 'Iceland',
      code: 'IS',
      dialCode: '+354',
      currency: 'ISK',
      flag: '🇮🇸',
    ),
    Country(
      name: 'India',
      code: 'IN',
      dialCode: '+91',
      currency: 'INR',
      flag: '🇮🇳',
    ),
    Country(
      name: 'Indonesia',
      code: 'ID',
      dialCode: '+62',
      currency: 'IDR',
      flag: '🇮🇩',
    ),
    Country(
      name: 'Iran',
      code: 'IR',
      dialCode: '+98',
      currency: 'IRR',
      flag: '🇮🇷',
    ),
    Country(
      name: 'Iraq',
      code: 'IQ',
      dialCode: '+964',
      currency: 'IQD',
      flag: '🇮🇶',
    ),
    Country(
      name: 'Ireland',
      code: 'IE',
      dialCode: '+353',
      currency: 'EUR',
      flag: '🇮🇪',
    ),
    Country(
      name: 'Israel',
      code: 'IL',
      dialCode: '+972',
      currency: 'ILS',
      flag: '🇮🇱',
    ),
    Country(
      name: 'Italy',
      code: 'IT',
      dialCode: '+39',
      currency: 'EUR',
      flag: '🇮🇹',
    ),
    Country(
      name: 'Jamaica',
      code: 'JM',
      dialCode: '+1-876',
      currency: 'JMD',
      flag: '🇯🇲',
    ),
    Country(
      name: 'Japan',
      code: 'JP',
      dialCode: '+81',
      currency: 'JPY',
      flag: '🇯🇵',
    ),
    Country(
      name: 'Jordan',
      code: 'JO',
      dialCode: '+962',
      currency: 'JOD',
      flag: '🇯🇴',
    ),
    Country(
      name: 'Kazakhstan',
      code: 'KZ',
      dialCode: '+7',
      currency: 'KZT',
      flag: '🇰🇿',
    ),
    Country(
      name: 'Kenya',
      code: 'KE',
      dialCode: '+254',
      currency: 'KES',
      flag: '🇰🇪',
    ),
    Country(
      name: 'Kiribati',
      code: 'KI',
      dialCode: '+686',
      currency: 'AUD',
      flag: '🇰🇮',
    ),
    Country(
      name: 'Kuwait',
      code: 'KW',
      dialCode: '+965',
      currency: 'KWD',
      flag: '🇰🇼',
    ),
    Country(
      name: 'Kyrgyzstan',
      code: 'KG',
      dialCode: '+996',
      currency: 'KGS',
      flag: '🇰🇬',
    ),
    Country(
      name: 'Laos',
      code: 'LA',
      dialCode: '+856',
      currency: 'LAK',
      flag: '🇱🇦',
    ),
    Country(
      name: 'Latvia',
      code: 'LV',
      dialCode: '+371',
      currency: 'EUR',
      flag: '🇱🇻',
    ),
    Country(
      name: 'Lebanon',
      code: 'LB',
      dialCode: '+961',
      currency: 'LBP',
      flag: '🇱🇧',
    ),
    Country(
      name: 'Lesotho',
      code: 'LS',
      dialCode: '+266',
      currency: 'LSL',
      flag: '🇱🇸',
    ),
    Country(
      name: 'Liberia',
      code: 'LR',
      dialCode: '+231',
      currency: 'LRD',
      flag: '🇱🇷',
    ),
    Country(
      name: 'Libya',
      code: 'LY',
      dialCode: '+218',
      currency: 'LYD',
      flag: '🇱🇾',
    ),
    Country(
      name: 'Liechtenstein',
      code: 'LI',
      dialCode: '+423',
      currency: 'CHF',
      flag: '🇱🇮',
    ),
    Country(
      name: 'Lithuania',
      code: 'LT',
      dialCode: '+370',
      currency: 'EUR',
      flag: '🇱🇹',
    ),
    Country(
      name: 'Luxembourg',
      code: 'LU',
      dialCode: '+352',
      currency: 'EUR',
      flag: '🇱🇺',
    ),
    Country(
      name: 'Macau',
      code: 'MO',
      dialCode: '+853',
      currency: 'MOP',
      flag: '🇲🇴',
    ),
    Country(
      name: 'Macedonia',
      code: 'MK',
      dialCode: '+389',
      currency: 'MKD',
      flag: '🇲🇰',
    ),
    Country(
      name: 'Madagascar',
      code: 'MG',
      dialCode: '+261',
      currency: 'MGA',
      flag: '🇲🇬',
    ),
    Country(
      name: 'Malawi',
      code: 'MW',
      dialCode: '+265',
      currency: 'MWK',
      flag: '🇲🇼',
    ),
    Country(
      name: 'Malaysia',
      code: 'MY',
      dialCode: '+60',
      currency: 'MYR',
      flag: '🇲🇾',
    ),
    Country(
      name: 'Maldives',
      code: 'MV',
      dialCode: '+960',
      currency: 'MVR',
      flag: '🇲🇻',
    ),
    Country(
      name: 'Mali',
      code: 'ML',
      dialCode: '+223',
      currency: 'XOF',
      flag: '🇲🇱',
    ),
    Country(
      name: 'Malta',
      code: 'MT',
      dialCode: '+356',
      currency: 'EUR',
      flag: '🇲🇹',
    ),
    Country(
      name: 'Marshall Islands',
      code: 'MH',
      dialCode: '+692',
      currency: 'USD',
      flag: '🇲🇭',
    ),
    Country(
      name: 'Martinique',
      code: 'MQ',
      dialCode: '+596',
      currency: 'EUR',
      flag: '🇲🇶',
    ),
    Country(
      name: 'Mauritania',
      code: 'MR',
      dialCode: '+222',
      currency: 'MRO',
      flag: '🇲🇷',
    ),
    Country(
      name: 'Mauritius',
      code: 'MU',
      dialCode: '+230',
      currency: 'MUR',
      flag: '🇲🇺',
    ),
    Country(
      name: 'Mayotte',
      code: 'YT',
      dialCode: '+262',
      currency: 'EUR',
      flag: '🇾🇹',
    ),
    Country(
      name: 'Mexico',
      code: 'MX',
      dialCode: '+52',
      currency: 'MXN',
      flag: '🇲🇽',
    ),
    Country(
      name: 'Micronesia',
      code: 'FM',
      dialCode: '+691',
      currency: 'USD',
      flag: '🇫🇲',
    ),
    Country(
      name: 'Moldova',
      code: 'MD',
      dialCode: '+373',
      currency: 'MDL',
      flag: '🇲🇩',
    ),
    Country(
      name: 'Monaco',
      code: 'MC',
      dialCode: '+377',
      currency: 'EUR',
      flag: '🇲🇨',
    ),
    Country(
      name: 'Mongolia',
      code: 'MN',
      dialCode: '+976',
      currency: 'MNT',
      flag: '🇲🇳',
    ),
    Country(
      name: 'Montenegro',
      code: 'ME',
      dialCode: '+382',
      currency: 'EUR',
      flag: '🇲🇪',
    ),
    Country(
      name: 'Montserrat',
      code: 'MS',
      dialCode: '+1-664',
      currency: 'XCD',
      flag: '🇲🇸',
    ),
    Country(
      name: 'Morocco',
      code: 'MA',
      dialCode: '+212',
      currency: 'MAD',
      flag: '🇲🇦',
    ),
    Country(
      name: 'Mozambique',
      code: 'MZ',
      dialCode: '+258',
      currency: 'MZN',
      flag: '🇲🇿',
    ),
    Country(
      name: 'Myanmar',
      code: 'MM',
      dialCode: '+95',
      currency: 'MMK',
      flag: '🇲🇲',
    ),
    Country(
      name: 'Namibia',
      code: 'NA',
      dialCode: '+264',
      currency: 'NAD',
      flag: '🇳🇦',
    ),
    Country(
      name: 'Nauru',
      code: 'NR',
      dialCode: '+674',
      currency: 'AUD',
      flag: '🇳🇷',
    ),
    Country(
      name: 'Nepal',
      code: 'NP',
      dialCode: '+977',
      currency: 'NPR',
      flag: '🇳🇵',
    ),
    Country(
      name: 'Netherlands',
      code: 'NL',
      dialCode: '+31',
      currency: 'EUR',
      flag: '🇳🇱',
    ),
    Country(
      name: 'New Caledonia',
      code: 'NC',
      dialCode: '+687',
      currency: 'XPF',
      flag: '🇳🇨',
    ),
    Country(
      name: 'New Zealand',
      code: 'NZ',
      dialCode: '+64',
      currency: 'NZD',
      flag: '🇳🇿',
    ),
    Country(
      name: 'Nicaragua',
      code: 'NI',
      dialCode: '+505',
      currency: 'NIO',
      flag: '🇳🇮',
    ),
    Country(
      name: 'Niger',
      code: 'NE',
      dialCode: '+227',
      currency: 'XOF',
      flag: '🇳🇪',
    ),
    Country(
      name: 'Nigeria',
      code: 'NG',
      dialCode: '+234',
      currency: 'NGN',
      flag: '🇳🇬',
    ),
    Country(
      name: 'Niue',
      code: 'NU',
      dialCode: '+683',
      currency: 'NZD',
      flag: '🇳🇺',
    ),
    Country(
      name: 'Norfolk Island',
      code: 'NF',
      dialCode: '+672',
      currency: 'AUD',
      flag: '🇳🇫',
    ),
    Country(
      name: 'North Korea',
      code: 'KP',
      dialCode: '+850',
      currency: 'KPW',
      flag: '🇰🇵',
    ),
    Country(
      name: 'Northern Mariana Islands',
      code: 'MP',
      dialCode: '+1-670',
      currency: 'USD',
      flag: '🇲🇵',
    ),
    Country(
      name: 'Norway',
      code: 'NO',
      dialCode: '+47',
      currency: 'NOK',
      flag: '🇳🇴',
    ),
    Country(
      name: 'Oman',
      code: 'OM',
      dialCode: '+968',
      currency: 'OMR',
      flag: '🇴🇲',
    ),
    Country(
      name: 'Pakistan',
      code: 'PK',
      dialCode: '+92',
      currency: 'PKR',
      flag: '🇵🇰',
    ),
    Country(
      name: 'Palau',
      code: 'PW',
      dialCode: '+680',
      currency: 'USD',
      flag: '🇵🇼',
    ),
    Country(
      name: 'Palestine',
      code: 'PS',
      dialCode: '+970',
      currency: 'ILS',
      flag: '🇵🇸',
    ),
    Country(
      name: 'Panama',
      code: 'PA',
      dialCode: '+507',
      currency: 'PAB',
      flag: '🇵🇦',
    ),
    Country(
      name: 'Papua New Guinea',
      code: 'PG',
      dialCode: '+675',
      currency: 'PGK',
      flag: '🇵🇬',
    ),
    Country(
      name: 'Paraguay',
      code: 'PY',
      dialCode: '+595',
      currency: 'PYG',
      flag: '🇵🇾',
    ),
    Country(
      name: 'Peru',
      code: 'PE',
      dialCode: '+51',
      currency: 'PEN',
      flag: '🇵🇪',
    ),
    Country(
      name: 'Philippines',
      code: 'PH',
      dialCode: '+63',
      currency: 'PHP',
      flag: '🇵🇭',
    ),
    Country(
      name: 'Poland',
      code: 'PL',
      dialCode: '+48',
      currency: 'PLN',
      flag: '🇵🇱',
    ),
    Country(
      name: 'Portugal',
      code: 'PT',
      dialCode: '+351',
      currency: 'EUR',
      flag: '🇵🇹',
    ),
    Country(
      name: 'Puerto Rico',
      code: 'PR',
      dialCode: '+1-787',
      currency: 'USD',
      flag: '🇵🇷',
    ),
    Country(
      name: 'Qatar',
      code: 'QA',
      dialCode: '+974',
      currency: 'QAR',
      flag: '🇶🇦',
    ),
    Country(
      name: 'Romania',
      code: 'RO',
      dialCode: '+40',
      currency: 'RON',
      flag: '🇷🇴',
    ),
    Country(
      name: 'Russia',
      code: 'RU',
      dialCode: '+7',
      currency: 'RUB',
      flag: '🇷🇺',
    ),
    Country(
      name: 'Rwanda',
      code: 'RW',
      dialCode: '+250',
      currency: 'RWF',
      flag: '🇷🇼',
    ),
    Country(
      name: 'Saint Kitts and Nevis',
      code: 'KN',
      dialCode: '+1-869',
      currency: 'XCD',
      flag: '🇰🇳',
    ),
    Country(
      name: 'Saint Lucia',
      code: 'LC',
      dialCode: '+1-758',
      currency: 'XCD',
      flag: '🇱🇨',
    ),
    Country(
      name: 'Saint Vincent and the Grenadines',
      code: 'VC',
      dialCode: '+1-784',
      currency: 'XCD',
      flag: '🇻🇨',
    ),
    Country(
      name: 'Samoa',
      code: 'WS',
      dialCode: '+685',
      currency: 'WST',
      flag: '🇼🇸',
    ),
    Country(
      name: 'San Marino',
      code: 'SM',
      dialCode: '+378',
      currency: 'EUR',
      flag: '🇸🇲',
    ),
    Country(
      name: 'Sao Tome and Principe',
      code: 'ST',
      dialCode: '+239',
      currency: 'STD',
      flag: '🇸🇹',
    ),
    Country(
      name: 'Saudi Arabia',
      code: 'SA',
      dialCode: '+966',
      currency: 'SAR',
      flag: '🇸🇦',
    ),
    Country(
      name: 'Senegal',
      code: 'SN',
      dialCode: '+221',
      currency: 'XOF',
      flag: '🇸🇳',
    ),
    Country(
      name: 'Serbia',
      code: 'RS',
      dialCode: '+381',
      currency: 'RSD',
      flag: '🇷🇸',
    ),
    Country(
      name: 'Seychelles',
      code: 'SC',
      dialCode: '+248',
      currency: 'SCR',
      flag: '🇸🇨',
    ),
    Country(
      name: 'Sierra Leone',
      code: 'SL',
      dialCode: '+232',
      currency: 'SLL',
      flag: '🇸🇱',
    ),
    Country(
      name: 'Singapore',
      code: 'SG',
      dialCode: '+65',
      currency: 'SGD',
      flag: '🇸🇬',
    ),
    Country(
      name: 'Slovakia',
      code: 'SK',
      dialCode: '+421',
      currency: 'EUR',
      flag: '🇸🇰',
    ),
    Country(
      name: 'Slovenia',
      code: 'SI',
      dialCode: '+386',
      currency: 'EUR',
      flag: '🇸🇮',
    ),
    Country(
      name: 'Solomon Islands',
      code: 'SB',
      dialCode: '+677',
      currency: 'SBD',
      flag: '🇸🇧',
    ),
    Country(
      name: 'Somalia',
      code: 'SO',
      dialCode: '+252',
      currency: 'SOS',
      flag: '🇸🇴',
    ),
    Country(
      name: 'South Africa',
      code: 'ZA',
      dialCode: '+27',
      currency: 'ZAR',
      flag: '🇿🇦',
    ),
    Country(
      name: 'South Korea',
      code: 'KR',
      dialCode: '+82',
      currency: 'KRW',
      flag: '🇰🇷',
    ),
    Country(
      name: 'South Sudan',
      code: 'SS',
      dialCode: '+211',
      currency: 'SSP',
      flag: '🇸🇸',
    ),
    Country(
      name: 'Spain',
      code: 'ES',
      dialCode: '+34',
      currency: 'EUR',
      flag: '🇪🇸',
    ),
    Country(
      name: 'Sri Lanka',
      code: 'LK',
      dialCode: '+94',
      currency: 'LKR',
      flag: '🇱🇰',
    ),
    Country(
      name: 'Sudan',
      code: 'SD',
      dialCode: '+249',
      currency: 'SDG',
      flag: '🇸🇩',
    ),
    Country(
      name: 'Suriname',
      code: 'SR',
      dialCode: '+597',
      currency: 'SRD',
      flag: '🇸🇷',
    ),
    Country(
      name: 'Sweden',
      code: 'SE',
      dialCode: '+46',
      currency: 'SEK',
      flag: '🇸🇪',
    ),
    Country(
      name: 'Switzerland',
      code: 'CH',
      dialCode: '+41',
      currency: 'CHF',
      flag: '🇨🇭',
    ),
    Country(
      name: 'Syria',
      code: 'SY',
      dialCode: '+963',
      currency: 'SYP',
      flag: '🇸🇾',
    ),
    Country(
      name: 'Taiwan',
      code: 'TW',
      dialCode: '+886',
      currency: 'TWD',
      flag: '🇹🇼',
    ),
    Country(
      name: 'Tajikistan',
      code: 'TJ',
      dialCode: '+992',
      currency: 'TJS',
      flag: '🇹🇯',
    ),
    Country(
      name: 'Tanzania',
      code: 'TZ',
      dialCode: '+255',
      currency: 'TZS',
      flag: '🇹🇿',
    ),
    Country(
      name: 'Thailand',
      code: 'TH',
      dialCode: '+66',
      currency: 'THB',
      flag: '🇹🇭',
    ),
    Country(
      name: 'Timor-Leste',
      code: 'TL',
      dialCode: '+670',
      currency: 'USD',
      flag: '🇹🇱',
    ),
    Country(
      name: 'Togo',
      code: 'TG',
      dialCode: '+228',
      currency: 'XOF',
      flag: '🇹🇬',
    ),
    Country(
      name: 'Tonga',
      code: 'TO',
      dialCode: '+676',
      currency: 'TOP',
      flag: '🇹🇴',
    ),
    Country(
      name: 'Trinidad and Tobago',
      code: 'TT',
      dialCode: '+1-868',
      currency: 'TTD',
      flag: '🇹🇹',
    ),
    Country(
      name: 'Tunisia',
      code: 'TN',
      dialCode: '+216',
      currency: 'TND',
      flag: '🇹🇳',
    ),
    Country(
      name: 'Turkey',
      code: 'TR',
      dialCode: '+90',
      currency: 'TRY',
      flag: '🇹🇷',
    ),
    Country(
      name: 'Turkmenistan',
      code: 'TM',
      dialCode: '+993',
      currency: 'TMT',
      flag: '🇹🇲',
    ),
    Country(
      name: 'Tuvalu',
      code: 'TV',
      dialCode: '+688',
      currency: 'AUD',
      flag: '🇹🇻',
    ),
    Country(
      name: 'Uganda',
      code: 'UG',
      dialCode: '+256',
      currency: 'UGX',
      flag: '🇺🇬',
    ),
    Country(
      name: 'Ukraine',
      code: 'UA',
      dialCode: '+380',
      currency: 'UAH',
      flag: '🇺🇦',
    ),
    Country(
      name: 'United Arab Emirates',
      code: 'AE',
      dialCode: '+971',
      currency: 'AED',
      flag: '🇦🇪',
    ),
    Country(
      name: 'United Kingdom',
      code: 'GB',
      dialCode: '+44',
      currency: 'GBP',
      flag: '🇬🇧',
    ),
    Country(
      name: 'United States',
      code: 'US',
      dialCode: '+1',
      currency: 'USD',
      flag: '🇺🇸',
    ),
    Country(
      name: 'Uruguay',
      code: 'UY',
      dialCode: '+598',
      currency: 'UYU',
      flag: '🇺🇾',
    ),
    Country(
      name: 'Uzbekistan',
      code: 'UZ',
      dialCode: '+998',
      currency: 'UZS',
      flag: '🇺🇿',
    ),
    Country(
      name: 'Vanuatu',
      code: 'VU',
      dialCode: '+678',
      currency: 'VUV',
      flag: '🇻🇺',
    ),
    Country(
      name: 'Venezuela',
      code: 'VE',
      dialCode: '+58',
      currency: 'VEF',
      flag: '🇻🇪',
    ),
    Country(
      name: 'Vietnam',
      code: 'VN',
      dialCode: '+84',
      currency: 'VND',
      flag: '🇻🇳',
    ),
    Country(
      name: 'Virgin Islands, British',
      code: 'VG',
      dialCode: '+1-284',
      currency: 'USD',
      flag: '🇻🇬',
    ),
    Country(
      name: 'Virgin Islands, U.S.',
      code: 'VI',
      dialCode: '+1-340',
      currency: 'USD',
      flag: '🇻🇮',
    ),
    Country(
      name: 'Yemen',
      code: 'YE',
      dialCode: '+967',
      currency: 'YER',
      flag: '🇾🇪',
    ),
    Country(
      name: 'Zambia',
      code: 'ZM',
      dialCode: '+260',
      currency: 'ZMW',
      flag: '🇿🇲',
    ),
    Country(
      name: 'Zimbabwe',
      code: 'ZW',
      dialCode: '+263',
      currency: 'USD',
      flag: '🇿🇼',
    ),
  ];

  Map<String, dynamic> toJson() => {
    'name': name,
    'code': code,
    'dialCode': dialCode,
    'currency': currency,
    'flag': flag,
  };

  factory Country.fromJson(Map<String, dynamic> json) {
    return Country(
      name: json['name'] ?? '',
      code: json['code'] ?? '',
      dialCode: json['dialCode'] ?? '',
      currency: json['currency'] ?? '',
      flag: json['flag'] ?? '',
    );
  }
}
