// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3I1Y7_EY0-apZ_IJ079q7mZDz-9Gx-Cc',
    appId: '1:514046157450:web:95b47e50ab7258060e4373',
    messagingSenderId: '514046157450',
    projectId: 'rightlogistics-a3e1a',
    authDomain: 'rightlogistics-a3e1a.firebaseapp.com',
    storageBucket: 'rightlogistics-a3e1a.firebasestorage.app',
    measurementId: 'G-D4FRJE65NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV-nR21ENiUWEjfRreuIk2a660S81GK3s',
    appId: '1:514046157450:android:ec9fb7b150bf06970e4373',
    messagingSenderId: '514046157450',
    projectId: 'rightlogistics-a3e1a',
    storageBucket: 'rightlogistics-a3e1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC5f92_gSDkyzeZusi8hAagbepsbDuMCg',
    appId: '1:514046157450:ios:1a461935393c0cac0e4373',
    messagingSenderId: '514046157450',
    projectId: 'rightlogistics-a3e1a',
    storageBucket: 'rightlogistics-a3e1a.firebasestorage.app',
    iosBundleId: 'com.codeink.technologies.rightlogistics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC5f92_gSDkyzeZusi8hAagbepsbDuMCg',
    appId: '1:514046157450:ios:1a461935393c0cac0e4373',
    messagingSenderId: '514046157450',
    projectId: 'rightlogistics-a3e1a',
    storageBucket: 'rightlogistics-a3e1a.firebasestorage.app',
    iosBundleId: 'com.codeink.technologies.rightlogistics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3I1Y7_EY0-apZ_IJ079q7mZDz-9Gx-Cc',
    appId: '1:514046157450:web:e3563b8e004e40bf0e4373',
    messagingSenderId: '514046157450',
    projectId: 'rightlogistics-a3e1a',
    authDomain: 'rightlogistics-a3e1a.firebaseapp.com',
    storageBucket: 'rightlogistics-a3e1a.firebasestorage.app',
    measurementId: 'G-2QS9E66ENQ',
  );
}
